### ISSUE TITLE
Problem get data method listContacts

### ISSUE THREAD

**Issue by gfernandez87** [vdavid/node-mautic#25] opened 2021-06-18 06:58 UTC
Dear good morning when I try to use the method to list the contacts (listContacts), it only returns the id, but not all the information, such as name, surname, etc.

![image](https://user-images.githubusercontent.com/6432486/122519896-5d06fa00-cfe9-11eb-80be-8dc02490845d.png)

Values fields.all

![image](https://user-images.githubusercontent.com/6432486/122520177-aa836700-cfe9-11eb-8ad7-8fca6eeee41a.png)

I would appreciate if you can help find a solution.
Thanks!

**Comment by vdavid** [comment] 2021-06-18 07:21
I'm not at my computer right now, but if I rememver correctly, that data is in the "fields" object. To make sure, give it a try, or read Mautic's docs.
Did this answer solve it for you?

**Comment by vdavid** [comment] 2021-06-18 07:25
Ah, sorry, just re-read youe message. Then it indeed should be in the "fields" object.
Are you sure that those fields are not null in Mautic for this contact?
Also, what happens if you use software like Postman or Insomnia to send the requests manually? Does Mautic return the name when called that way?

**Comment by gfernandez87** [comment] 2021-06-18 13:57
Dear first of all, thank you very much for your answer. There I was testing with postman, and apparently it does the same. The truth is that it is very strange, look at this postman query, I happen to only return two records, but I return more, it is as if it did not take the parameters that I pass:

/api/contacts

![image](https://user-images.githubusercontent.com/6432486/122572120-cf94cb80-d023-11eb-9152-662183fd2bf7.png)

Result return more two:

![image](https://user-images.githubusercontent.com/6432486/122572236-ed623080-d023-11eb-9e3c-d2b18710ee4a.png)

**Comment by vdavid** [comment] 2021-06-19 09:14
Sorry, mate, I'm not sure what's wrong.
But if Postman returns the same data, then the problem is not with the Node.js library.

My suggestion for you is to reach out to Mautic support or their community forums.
I'm sure they can help you figure out what's wrong.

**Comment by vdavid** [comment] 2021-06-19 09:14
I'll close this issue because it doesn't seem related to this library.

**Closed by vdavid** 2021-06-19 09:14 UTC
